/**
 * TNTの面に描く紋章。すべて 10行 × 14列。
 *   "."  描かない (地の色や帯がそのまま見える)
 *   "X"  主色 (ink)
 *   "o"  明色 (inkLight)
 *   "#"  暗色 (inkDark)
 *
 * 帯 (5〜10行) の中に収める必要はなく、上下にはみ出して本体の上にも描く。
 * はみ出した部分は縞の上に乗って読みにくくなるので、生成時に自動で
 * 1ドットの縁取りが付く (tools/generate-textures.mjs の drawGlyph)。
 */
export const EMBLEMS = {
  // ── 基本 ──────────────────────────────────────────────
  tnt: [
    "..............",
    "..............",
    "..............",
    "XXXX.X..X.XXXX",
    ".XX..XX.X..XX.",
    ".XX..XXXX..XX.",
    ".XX..X.XX..XX.",
    ".XX..X..X..XX.",
    "..............",
    "..............",
  ],
  dynamite: [
    "...........oX.",
    "..........oX..",
    ".........o....",
    "....XXXXXX....",
    "....XooooX....",
    "....XooooX....",
    "....XooooX....",
    "....XooooX....",
    "....XXXXXX....",
    "..............",
  ],

  // ── 核・破滅系 ────────────────────────────────────────
  radiation: [
    ".....XXXX.....",
    "....XXXXXX....",
    "....XXXXXX....",
    ".....XXXX.....",
    "......XX......",
    "..XX..XX..XX..",
    ".XXXX.XX.XXXX.",
    "XXXXX....XXXXX",
    "XXXX......XXXX",
    ".XX........XX.",
  ],
  mushroom: [
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "..XXXXXXXXXX..",
    "....XXXXXX....",
    ".....XXXX.....",
    ".....XXXX.....",
    ".....XXXX.....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
  ],
  mushroom_ring: [
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "o.XXXXXXXXXX.o",
    "o...XXXXXX...o",
    "o....XXXX....o",
    "o....XXXX....o",
    ".....XXXX.....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
  ],
  bomb: [
    "...........oX.",
    "..........oX..",
    ".........o....",
    "...XXXXXX.....",
    "..XXXXXXXX....",
    ".XXXXXXXXXX...",
    ".XXXXXXXXXX...",
    ".XXXXXXXXXX...",
    "..XXXXXXXX....",
    "...XXXXXX.....",
  ],
  atom: [
    "...XXXXXXXX...",
    ".XX........XX.",
    "X............X",
    "X....XXXX....X",
    "o...XXXXXX...o",
    "o...XXXXXX...o",
    "X....XXXX....X",
    "X............X",
    ".XX........XX.",
    "...XXXXXXXX...",
  ],
  skull: [
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    ".XXX..XX..XXX.",
    ".XXX..XX..XXX.",
    ".XXXXXXXXXXXX.",
    ".XXXXXXXXXXXX.",
    "..XX.XXXX.XX..",
    "..XX.XXXX.XX..",
    "...XXXXXXXX...",
  ],
  bigskull: [
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "XXX.oo..oo.XXX",
    "XXX.oo..oo.XXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XX.X.XX.X.XX.",
    ".XX.X.XX.X.XX.",
    "..XXXXXXXXXX..",
  ],

  // ── 温度・天候 ────────────────────────────────────────
  flame: [
    "......XX......",
    ".....XXXX.....",
    "....XXXXXX....",
    "...XXX..XXX...",
    "..XXX....XXX..",
    "..XXX.oo.XXX..",
    "..XXXoooXXXX..",
    "...XXXooXXX...",
    "...XXXXXXXX...",
    "....XXXXXX....",
  ],
  lava: [
    "..............",
    ".....o...o....",
    "....oXo.oXo...",
    "..X..X...X..X.",
    ".XXX.XX.XX.XXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
  ],
  snowflake: [
    "......XX......",
    "..X...XX...X..",
    "...X..XX..X...",
    "....X.XX.X....",
    "XXXX..XX..XXXX",
    "XXXX..XX..XXXX",
    "....X.XX.X....",
    "...X..XX..X...",
    "..X...XX...X..",
    "......XX......",
  ],
  glacier: [
    "..............",
    "......X.......",
    ".....XXX......",
    "....XXXXX.....",
    "...XXXXXXX..X.",
    "..XXXXXXXXXXX.",
    ".XXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
  ],
  droplet: [
    "......XX......",
    ".....XXXX.....",
    "....XXXXXX....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    "..XXXoooXXXX..",
    "..XXXoooXXXX..",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    ".....XXXX.....",
  ],
  wave: [
    "..............",
    ".......XXXX...",
    ".....XXXXXXX..",
    "...XXXX...XXX.",
    "..XXX.......XX",
    ".XX...........",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
  ],
  bolt: [
    "........XXXX..",
    ".......XXXX...",
    "......XXXX....",
    ".....XXXX.....",
    "...XXXXXXXX...",
    ".....XXXX.....",
    "....XXXX......",
    "...XXXX.......",
    "..XXXX........",
    ".XXX..........",
  ],
  cloud: [
    ".....XXXX.....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "..o...o...o...",
    ".o...o...o....",
    "o...o...o.....",
  ],
  sun: [
    "...X..XX..X...",
    "....X.XX.X....",
    ".....XXXX.....",
    "X...XXXXXX...X",
    "XX.XXXXXXXX.XX",
    "XX.XXXXXXXX.XX",
    "X...XXXXXX...X",
    ".....XXXX.....",
    "....X.XX.X....",
    "...X..XX..X...",
  ],
  moon: [
    "....XXXX...o..",
    "..XXXXXX......",
    ".XXXXX....o...",
    ".XXXX.........",
    "XXXX......o...",
    "XXXX..........",
    ".XXXX.....o...",
    ".XXXXX........",
    "..XXXXXX..o...",
    "....XXXX......",
  ],
  daynight: [
    "..XXXX...oooo.",
    ".XXXXXX.oo..oo",
    "XXXXXXX.o.....",
    "XXXXXXX.o.....",
    "XXXXXXX.o.....",
    "XXXXXXX.o.....",
    "XXXXXXX.o.....",
    "XXXXXXX.o.....",
    ".XXXXXX.oo..oo",
    "..XXXX...oooo.",
  ],

  // ── 力・移動 ──────────────────────────────────────────
  arrow_down: [
    ".....XXXX.....",
    ".....XXXX.....",
    ".....XXXX.....",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "....XXXXXX....",
    ".....XXXX.....",
    "......XX......",
  ],
  arrow_up: [
    "......XX......",
    ".....XXXX.....",
    "....XXXXXX....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    ".....XXXX.....",
    ".....XXXX.....",
    ".....XXXX.....",
  ],
  rocket: [
    "......XX......",
    ".....XXXX.....",
    "....XXooXX....",
    "....XXooXX....",
    "....XXooXX....",
    "...XXXXXXXX...",
    "..XX.XXXX.XX..",
    ".XX..XXXX..XX.",
    ".....oooo.....",
    "......oo......",
  ],
  speed: [
    "..............",
    "..XXX...XXX...",
    ".XXXX..XXXX...",
    "XXXX..XXXX....",
    "XXX..XXXX.....",
    "XXX..XXXX.....",
    "XXXX..XXXX....",
    ".XXXX..XXXX...",
    "..XXX...XXX...",
    "..............",
  ],
  bounce: [
    "....XXXXXX....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "....XXXXXX....",
    "..............",
    "..............",
    "oooooooooooooo",
  ],
  slime_face: [
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "XXX..XXXX..XXX",
    "XXX..XXXX..XXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XX.X.XXXX.X.XX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
  ],
  magnet: [
    "XXXX......XXXX",
    "XXXX......XXXX",
    "XXXX......XXXX",
    "XXXX......XXXX",
    "XXXX......XXXX",
    "XXXXX....XXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "..oooo..oooo..",
    "..oooo..oooo..",
  ],
  question: [
    "...XXXXXXXX...",
    "..XXX....XXX..",
    "..XX......XX..",
    "..........XX..",
    ".........XX...",
    "......XXX.....",
    "......XX......",
    "......XX......",
    "..............",
    "......XX......",
  ],
  void: [
    "....oooooo....",
    "..oo......oo..",
    ".o..........o.",
    "o............o",
    "o............o",
    "o............o",
    "o............o",
    ".o..........o.",
    "..oo......oo..",
    "....oooooo....",
  ],
  suction: [
    "XXX........XXX",
    ".XXX......XXX.",
    "..XXX....XXX..",
    "...XXX..XXX...",
    "....XXXXXX....",
    "....XXXXXX....",
    "...XXX..XXX...",
    "..XXX....XXX..",
    ".XXX......XXX.",
    "XXX........XXX",
  ],
  portal: [
    "...XXXXXXXX...",
    ".XXooooooooXX.",
    "XXoooooooooXXX",
    "Xoo.XXXXXX.ooX",
    "Xoo.XXXXXX.ooX",
    "Xoo.XXXXXX.ooX",
    "Xoo.XXXXXX.ooX",
    "XXoooooooooXXX",
    ".XXooooooooXX.",
    "...XXXXXXXX...",
  ],
  island: [
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "....XXXXXX....",
    ".....XXXX.....",
    "......XX......",
  ],
  swap: [
    "...X..........",
    "..X...........",
    "XXXXXXXXXXXXX.",
    "..X...........",
    "...X..........",
    "..............",
    "..........X...",
    "...........X..",
    ".XXXXXXXXXXXXX",
    "...........X..",
  ],
  beam: [
    "..............",
    "..XXXXXXXXXX..",
    "..............",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "..............",
    "..XXXXXXXXXX..",
    "..............",
  ],

  // ── 生き物 ────────────────────────────────────────────
  heart: [
    "..XXX....XXX..",
    ".XXXXX..XXXXX.",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    ".....XXXX.....",
    "......XX......",
  ],
  creeper: [
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XX...XXXX...XX",
    "XX...XXXX...XX",
    "XXXXXXXXXXXXXX",
    "XXXX......XXXX",
    "XXX........XXX",
    "XXX..XXXX..XXX",
    "XXX..XXXX..XXX",
    "XXXXXXXXXXXXXX",
  ],
  bee: [
    ".oo........oo.",
    "oooo......oooo",
    ".oo........oo.",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    "..XX..XX..XX..",
    "..XX..XX..XX..",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "......XX......",
  ],
  drip: [
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XX...XX...XX.",
    ".XX...XX...XX.",
    ".XX...XX...XX.",
    "..X....X....X.",
    "..o....o....o.",
    "..o....o....o.",
    "..............",
  ],
  paw: [
    ".XXX..XXX..XXX",
    ".XXX..XXX..XXX",
    ".XXX..XXX..XXX",
    "..............",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
  ],
  snowman: [
    ".....XXXX.....",
    "....XXXXXX....",
    "....X#XX#X....",
    "....XXXXXX....",
    ".....XXXX.....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    "..XXX.XX.XXX..",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
  ],
  ghost: [
    "....XXXXXX....",
    "..XXXXXXXXXX..",
    ".XX........XX.",
    ".X..XX..XX..X.",
    ".X..XX..XX..X.",
    ".X..........X.",
    ".X..........X.",
    ".X..........X.",
    ".X...X..X...X.",
    "..XXX.XX.XXX..",
  ],
  ufo: [
    "..............",
    ".....XXXX.....",
    "....XooooX....",
    "....XooooX....",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXoXXoXXoXXoXX",
    ".XXXXXXXXXXXX.",
    "..o...o...o...",
    "...o...o...o..",
  ],
  web: [
    "X.....XX.....X",
    ".X....XX....X.",
    "..X..XXXX..X..",
    "...XXXXXXXX...",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "...XXXXXXXX...",
    "..X..XXXX..X..",
    ".X....XX....X.",
    "X.....XX.....X",
  ],
  flask: [
    "....XXXXXX....",
    "....X....X....",
    "....X....X....",
    "...XX....XX...",
    "..XX......XX..",
    ".XX........XX.",
    ".XooooooooooX.",
    ".XooooooooooX.",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
  ],
  eye: [
    "..............",
    "...XXXXXXXX...",
    ".XXooooooooXX.",
    "XXoooo##ooooXX",
    "Xooo######oooX",
    "Xooo######oooX",
    "XXoooo##ooooXX",
    ".XXooooooooXX.",
    "...XXXXXXXX...",
    "..............",
  ],

  // ── 自然・地形 ────────────────────────────────────────
  grass: [
    "..X.....X.....",
    ".XXX...XXX..X.",
    ".XXX.X.XXX.XXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
  ],
  cactus: [
    "......XX......",
    "XXX...XX...XXX",
    "XXX...XX...XXX",
    "XXX...XX...XXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XX...XX...XX.",
    "......XX......",
    "......XX......",
    "......XX......",
  ],
  dune: [
    "..............",
    "..............",
    "......XX......",
    ".....XXXX.....",
    "....XXXXXX.XX.",
    "...XXXXXXXXXXX",
    "..XXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
  ],
  crack: [
    "......X.......",
    "......XX......",
    ".....XX.......",
    ".....XX...X...",
    "....XX...XX...",
    "....XX..XX....",
    "...XX...XX....",
    "...XX..XX.....",
    "..XX...XX.....",
    "..X....X......",
  ],
  meteor: [
    "o.............",
    ".oo...........",
    "..ooo.........",
    "...ooo..XXXX..",
    "....ooXXXXXXX.",
    ".....XXXXXXXXX",
    "....XXXXXXXXXX",
    "....XXXXXXXXX.",
    ".....XXXXXXX..",
    "......XXXXX...",
  ],
  hole: [
    "...XXXXXXXX...",
    ".XX########XX.",
    "X############X",
    "X############X",
    "X############X",
    "X############X",
    "X############X",
    "X############X",
    ".XX########XX.",
    "...XXXXXXXX...",
  ],
  crystal: [
    "......XX......",
    ".....XXXX.....",
    "....XXooXX....",
    "...XXXooXXX...",
    "..XXXXooXXXX..",
    "..XXXXooXXXX..",
    "...XXXooXXX...",
    "....XXooXX....",
    ".....XXXX.....",
    "......XX......",
  ],

  // ── 道具・その他 ──────────────────────────────────────
  gem: [
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    ".XoXoXoXoXoXX.",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "....XXXXXX....",
    ".....XXXX.....",
    "......XX......",
    "..............",
  ],
  clover: [
    "...XX....XX...",
    "..XXXX..XXXX..",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "..XXXX..XXXX..",
    "...XX.XX.XX...",
    "......XX......",
    "......XX......",
  ],
  star: [
    "......XX......",
    "......XX......",
    ".....XXXX.....",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "..XXXX..XXXX..",
    ".XXX......XXX.",
    "XX..........XX",
  ],
  firework: [
    "..o...XX...o..",
    "...o..XX..o...",
    "o...X.XX.X...o",
    ".o...XXXX...o.",
    "..XXXXXXXXXX..",
    ".o...XXXX...o.",
    "o...X.XX.X...o",
    "...o..XX..o...",
    "..o...XX...o..",
    "......XX......",
  ],
  confetti: [
    ".X...o....X..o",
    "...o...XX...X.",
    "X...oo....o...",
    "..oX...X..XX..",
    ".o...X...o...X",
    "X..o....X...o.",
    "...X..oo...X..",
    ".o....X...o..X",
    "..X..o...X....",
    "o...X...o...X.",
  ],
  note: [
    "...XXXXXXXXX..",
    "...XXXXXXXXX..",
    "...X.......X..",
    "...X.......X..",
    "...X.......X..",
    "...X.......X..",
    ".XXX.....XXX..",
    "XXXXX...XXXXX.",
    "XXXXX...XXXXX.",
    ".XXX.....XXX..",
  ],
  disco: [
    "...XXXXXXXX...",
    ".XXoXoXoXoXXX.",
    "XXoXoXoXoXoXXX",
    "XoXoXoXoXoXoXX",
    "XoXoXoXoXoXoXX",
    "XXoXoXoXoXoXXX",
    "XoXoXoXoXoXoXX",
    "XXoXoXoXoXoXXX",
    ".XXoXoXoXoXXX.",
    "...XXXXXXXX...",
  ],
  brick: [
    "XXXXXX.XXXXXXX",
    "XXXXXX.XXXXXXX",
    "XXXXXX.XXXXXXX",
    "..............",
    "XX.XXXXXXX.XXX",
    "XX.XXXXXXX.XXX",
    "XX.XXXXXXX.XXX",
    "..............",
    "XXXXXX.XXXXXXX",
    "XXXXXX.XXXXXXX",
  ],
  furnace: [
    "XXXXXXXXXXXXXX",
    "X............X",
    "X............X",
    "X.XXXXXXXXXX.X",
    "X.X........X.X",
    "X.X.oooooo.X.X",
    "X.X.oooooo.X.X",
    "X.XXXXXXXXXX.X",
    "X............X",
    "XXXXXXXXXXXXXX",
  ],
  wheat: [
    "......XX......",
    "..X...XX...X..",
    ".XXX..XX..XXX.",
    "..X..XXXX..X..",
    ".XXX..XX..XXX.",
    "..X..XXXX..X..",
    ".XXX..XX..XXX.",
    "..X...XX...X..",
    "......XX......",
    "......XX......",
  ],
  cutlery: [
    ".X.X.X....XXX.",
    ".X.X.X....XXX.",
    ".X.X.X....XXX.",
    ".XXXXX....XXX.",
    "..XXX.....XXX.",
    "..XXX......XX.",
    "..XXX......XX.",
    "..XXX......XX.",
    "..XXX......XX.",
    "..XXX......XX.",
  ],
  orb: [
    "o....XXXX....o",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "o....XXXX....o",
  ],
  arrows: [
    "...........X..",
    "..........XX..",
    ".........XXX..",
    "XXXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXX.",
    ".........XXX..",
    "..........XX..",
    "...........X..",
  ],

  // ── 常軌を逸したTNT ──────────────────────────────────
  singularity: [
    "....oooooo....",
    "..oo######oo..",
    ".o##########o.",
    "o############o",
    "o#####oo#####o",
    "o#####oo#####o",
    "o############o",
    ".o##########o.",
    "..oo######oo..",
    "....oooooo....",
  ],
  hourglass: [
    "XXXXXXXXXXXXXX",
    ".XooooooooooX.",
    "..XooooooooX..",
    "...XooooooX...",
    "....XooooX....",
    "....XooooX....",
    "...X......X...",
    "..X........X..",
    ".X..oooooo..X.",
    "XXXXXXXXXXXXXX",
  ],
  drill: [
    "..XXXXXXXXXX..",
    "..XooooooooX..",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "...X.XXXX.X...",
    "....XXXXXX....",
    "....X.XX.X....",
    ".....XXXX.....",
    "......XX......",
    "......XX......",
  ],
  collapse: [
    "XXXXXXXXXXXXXX",
    "XXXXX....XXXXX",
    "XXX........XXX",
    "XX..........XX",
    "..............",
    "....XX..XX....",
    "...XX....XX...",
    ".....XX.......",
    "........XX....",
    "...XX.....XX..",
  ],
  replicate: [
    ".....XXXX.....",
    ".....XXXX.....",
    ".....XXXX.....",
    "..............",
    "..XXXX..XXXX..",
    "..XXXX..XXXX..",
    "..............",
    ".XXX..XXX..XXX",
    ".XXX..XXX..XXX",
    "..............",
  ],

  // ── 建築 ────────────────────────────────────────
  tunnel: [
    "..............",
    "....XXXXXX....",
    "..XXXXXXXXXX..",
    "..XXooooooXX..",
    "..XXooooooXX..",
    "..XXooooooXX..",
    "..XXooooooXX..",
    "..XXooooooXX..",
    "..XXXXXXXXXX..",
    "..............",
  ],
  level: [
    "......XX......",
    "......XX......",
    "..X...XX...X..",
    "..XX..XX..XX..",
    "...XXXXXXXX...",
    "....XXXXXX....",
    "..............",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "..............",
  ],
  rampart: [
    "..............",
    "..............",
    "XX.XX.XX.XX.XX",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "X#XXX#XXX#XXXX",
    "XXXXXXXXXXXXXX",
    "XX#XXX#XXX#XXX",
    "XXXXXXXXXXXXXX",
    "..............",
  ],
  tower: [
    "...XX.XX.XX...",
    "...XXXXXXXX...",
    "...XXXXXXXX...",
    "....XXXXXX....",
    "....XoXXoX....",
    "....XXXXXX....",
    "....XXXXXX....",
    "....XoXXoX....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
  ],
  bridge: [
    "..............",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XX...XX...XX.",
    ".XX...XX...XX.",
    ".XX...XX...XX.",
    ".XX...XX...XX.",
    ".XX...XX...XX.",
    "XXXXXXXXXXXXXX",
    "..............",
  ],
  hut: [
    "......XX......",
    "....XXXXXX....",
    "..XXXXXXXXXX..",
    "XXXXXXXXXXXXXX",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..XXXXooXXXX..",
    "..XXXXooXXXX..",
    "..............",
  ],
  quarry: [
    "..............",
    "XXXXXXXXXXXXXX",
    "XX..........XX",
    "XXX........XXX",
    "XXXX......XXXX",
    "XXXXX....XXXXX",
    "XXXXXX..XXXXXX",
    "XXXXXXXXXXXXXX",
    "..............",
    "..............",
  ],
  stairs: [
    "XXX...........",
    "XXX...........",
    "XXXXXX........",
    "XXXXXX........",
    "XXXXXXXXX.....",
    "XXXXXXXXX.....",
    "XXXXXXXXXXXX..",
    "XXXXXXXXXXXX..",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
  ],
  road: [
    "..............",
    "XXXXXXXXXXXXXX",
    "XXXXXX..XXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXX..XXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXX..XXXXXX",
    "XXXXXXXXXXXXXX",
    "XXXXXX..XXXXXX",
    "..............",
  ],
  scaffold: [
    "..XX......XX..",
    "..XX......XX..",
    "..XXXXXXXXXX..",
    "..XX......XX..",
    "..XX......XX..",
    "..XXXXXXXXXX..",
    "..XX......XX..",
    "..XX......XX..",
    "..XXXXXXXXXX..",
    "..XX......XX..",
  ],

  // ── 兵器 ────────────────────────────────────────
  cluster: [
    ".....XXXX.....",
    "....XXXXXX....",
    "....XXXXXX....",
    ".....XXXX.....",
    "..............",
    "..XX..XX..XX..",
    "..XX..XX..XX..",
    "..............",
    ".XX.XX..XX.XX.",
    ".XX.XX..XX.XX.",
  ],
  napalm: [
    "......XX......",
    ".....XXXX.....",
    "....XXXXXX....",
    "....XXoXXX....",
    "....XXXXXX....",
    ".....XXXX.....",
    "..............",
    "XX..XXXX..XXXX",
    "XXXXXXXXXXXXXX",
    "..............",
  ],
  mine: [
    "..X..X..X..X..",
    "..X..X..X..X..",
    "..............",
    "....XXXXXX....",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    ".XXX#XXXX#XXX.",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "..............",
  ],
  missile: [
    "......XX......",
    ".....XXXX.....",
    ".....XXXX.....",
    "....XXXXXX....",
    "...XXXXXXXX...",
    "..XX.XXXX.XX..",
    "..X..XXXX..X..",
    ".....XXXX.....",
    "......oo......",
    ".....oooo.....",
  ],
  shrapnel: [
    "X....X..X....X",
    ".X...X..X...X.",
    "..X..XXXX..X..",
    "...XXXXXXXX...",
    "XXXXXXXXXXXXXX",
    "...XXXXXXXX...",
    "..X..XXXX..X..",
    ".X...X..X...X.",
    "X....X..X....X",
    "..............",
  ],
  emp: [
    "...XXXXXXXX...",
    "..XX......XX..",
    ".XX...XX...XX.",
    "XX...XX.....XX",
    "XX..XXXXX...XX",
    "XX.....XX...XX",
    ".XX...XX...XX.",
    "..XX.XX...XX..",
    "...XXXXXXXX...",
    "..............",
  ],
  bunker: [
    "......XX......",
    ".....XXXX.....",
    ".....XXXX.....",
    "......XX......",
    "XXXXXXXXXXXXXX",
    "XX#XXXXXX#XXXX",
    "......XX......",
    "XXXXXXXXXXXXXX",
    "XX#XXXXXX#XXXX",
    "......XX......",
  ],
  smoke: [
    "..............",
    "...XX...XX....",
    "..XXXX.XXXX...",
    ".XXXXXXXXXXX..",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "...XX..XX.....",
    "..............",
  ],
  gasmask: [
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXooXXXXXXooXX",
    "XXooXXXXXXooXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "....XXXXXX....",
    "....XXoXXX....",
    ".....XXXX.....",
  ],
  flak: [
    "X..X.....X..X.",
    ".XX.......XX..",
    "..X.XXXX..X...",
    "...XXXXXX.....",
    "...XXXXXX.....",
    "....XXXX......",
    "......XX......",
    ".....XXXX.....",
    "....XXXXXX....",
    "..XXXXXXXXXX..",
  ],

  // ── 宇宙 ────────────────────────────────────────
  supernova: [
    "..X....X....X.",
    "...X...X...X..",
    "....XXXXXXX...",
    "..XXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "..XXXXXXXXXXX.",
    "....XXXXXXX...",
    "...X...X...X..",
    "..X....X....X.",
    "..............",
  ],
  neutron: [
    "..............",
    "..XXXXXXXXXX..",
    ".X..........X.",
    "X....XXXX....X",
    "X...XXXXXX...X",
    "X...XXXXXX...X",
    "X....XXXX....X",
    ".X..........X.",
    "..XXXXXXXXXX..",
    "..............",
  ],
  wormhole: [
    "..XXXXXXXXXX..",
    ".X..........X.",
    "X...XXXXXX...X",
    "X..X......X..X",
    ".X..X....X..X.",
    "..X..XXXX..X..",
    "...X......X...",
    "....XXXXXX....",
    "......XX......",
    "......XX......",
  ],
  galaxy: [
    "...XXXXXX.....",
    ".XX......XX...",
    "X...XXXX...X..",
    "X..XX..XX..X..",
    "X..X.XXX.X.X..",
    "X..XX...XX.X..",
    "X...XXXXX..X..",
    ".XX.......XX..",
    "...XXXXXXX....",
    "..............",
  ],
  comet: [
    "..............",
    "..........XXX.",
    ".......XXXXXXX",
    "....XXXXXXXXX.",
    "..XXXXXXXX....",
    ".XXXXXX.......",
    "XXXXX.........",
    ".XXX..........",
    "..X...........",
    "..............",
  ],
  solarflare: [
    "X....XXXX....X",
    ".X..XXXXXX..X.",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "XXXXXXXXXXXXXX",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    ".X..XXXXXX..X.",
    "X....XXXX....X",
    "..............",
  ],
  nebula: [
    "...XX...XX....",
    "..XXXX.XXXX...",
    ".XXXXXXXXXXX..",
    "XXXoXXXXoXXXXX",
    "XXXXXXXXXXXXXX",
    ".XXXXoXXXXXXX.",
    "..XXXXXXXXXX..",
    "...XX..XXX....",
    "....X...X.....",
    "..............",
  ],
  bigbang: [
    "X.....XX.....X",
    ".X..XXXXXX..X.",
    "..X.XXXXXX.X..",
    "...XXXXXXXX...",
    "XXXXXXXXXXXXXX",
    "...XXXXXXXX...",
    "..X.XXXXXX.X..",
    ".X..XXXXXX..X.",
    "X.....XX.....X",
    "..............",
  ],

  // ── 属性の追加 ──────────────────────────────────
  acid: [
    "..XXXXXXXXXX..",
    "..X........X..",
    "..X.XXXXXX.X..",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "....XXXXXX....",
    ".....XXXX.....",
    "..X...XX...X..",
    ".XXX..XX..XXX.",
    "..X....X...X..",
  ],
  steam: [
    "..X..X..X..X..",
    ".X..X....X..X.",
    "..X..X..X..X..",
    "..............",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
  ],
  sandstorm: [
    "..............",
    "..XXXXXX......",
    "XXXX...XXXX...",
    "..XXXXXX..XXXX",
    "XXXX...XXXX...",
    "..XXXXXX..XXXX",
    "XXXX...XXXX...",
    "..XXXXXX......",
    "..............",
    "..............",
  ],
  geode: [
    ".......X......",
    "....X..X..X...",
    "....X.XXX.X...",
    "..X.XXXXXXX.X.",
    "..X.XXXXXXX.X.",
    ".XXXXXXXXXXXX.",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "...XXXXXXXX...",
    "..............",
  ],

  // ── 生物の追加 ──────────────────────────────────
  cat: [
    ".XX........XX.",
    ".XXX......XXX.",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
    "XXoXXXXXXXXoXX",
    "XXXXXXXXXXXXXX",
    "XX.XXXoXXX.XXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
  ],
  villager: [
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..oXXXXXXXXo..",
    "..XXXXXXXXXX..",
    "....XXXXXX....",
    "....XXXXXX....",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..............",
  ],
  golem: [
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    "..XoXXXXXXoX..",
    "..XXXXXXXXXX..",
    "....XXXXXX....",
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XX.XXXXXXXX.XX",
    "XX.XXXXXXXX.XX",
    "...XXX..XXX...",
  ],
  phantom: [
    "..............",
    "XX..........XX",
    "XXXX......XXXX",
    ".XXXXX..XXXXX.",
    "..XXXXXXXXXX..",
    "...XXoXXoXXX..",
    "....XXXXXX....",
    ".....XXXX.....",
    "......XX......",
    "..............",
  ],

  // ── 地形の追加 ──────────────────────────────────
  tree: [
    "......XX......",
    "....XXXXXX....",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "..XXXXXXXXXX..",
    "....XXXXXX....",
    "......XX......",
    "......XX......",
    ".....XXXX.....",
    "..............",
  ],
  cave: [
    "XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX",
    "XX.XX..XX..XXX",
    "X...X...X...XX",
    "X...........XX",
    "X............X",
    "XX..........XX",
    "XXX....X...XXX",
    "XXXX..XXX.XXXX",
    "XXXXXXXXXXXXXX",
  ],
  lake: [
    "..............",
    "...XXXXXXXX...",
    ".XXXXXXXXXXXX.",
    "XXoo.XXX.ooXXX",
    "XX.XXX.XXX.XXX",
    "XXoo.XXX.ooXXX",
    "XX.XXX.XXX.XXX",
    ".XXXXXXXXXXXX.",
    "...XXXXXXXX...",
    "..............",
  ],
  nether: [
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..XXoooooXXX..",
    "..XXoooooXXX..",
    "..XXoooooXXX..",
    "..XXoooooXXX..",
    "..XXoooooXXX..",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..............",
  ],

  // ── 便利の追加 ──────────────────────────────────
  crate: [
    "..............",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..XXXX##XXXX..",
    "..XXXX##XXXX..",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..XXXXXXXXXX..",
    "..............",
  ],
  torch: [
    "......XX......",
    ".....XXXX.....",
    "....XXoXXX....",
    ".....XXXX.....",
    "......XX......",
    "......XX......",
    "......XX......",
    "......XX......",
    "......XX......",
    "......XX......",
  ],
  beacon_glyph: [
    "....X....X....",
    "....X....X....",
    "....X....X....",
    "....X....X....",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    "..XXoooooXXX..",
    "..XXXXXXXXXX..",
    ".XXXXXXXXXXXX.",
    "XXXXXXXXXXXXXX",
  ],
  survey: [
    "...XXXXXX.....",
    "..XX....XX....",
    ".XX..XX..XX...",
    ".X..XXXX..X...",
    ".X..XXXX..X...",
    ".XX..XX..XX...",
    "..XX....XX....",
    "...XXXXXXXX...",
    ".........XXX..",
    "..........XXX.",
  ],

  // ── 移動の追加 ──────────────────────────────────
  elevator: [
    "XX....XX....XX",
    "XX...XXXX...XX",
    "XX..XXXXXX..XX",
    "XX.XXXXXXXX.XX",
    "XX....XX....XX",
    "XX....XX....XX",
    "XX....XX....XX",
    "XX....XX....XX",
    "XX....XX....XX",
    "XXXXXXXXXXXXXX",
  ],
  dash: [
    "..............",
    "XXXX....XX....",
    "....XX....XX..",
    "..XXX...XXX...",
    "XXXXXXXXXXXX..",
    "..XXX...XXX...",
    "....XX....XX..",
    "XXXX....XX....",
    "..............",
    "..............",
  ],

  // ── 演出の追加 ──────────────────────────────────
  aurora: [
    "..XX......XX..",
    ".XXXX....XXXX.",
    "XXXXXX..XXXXXX",
    "XXXXXXXXXXXXXX",
    ".XXXXXXXXXXXX.",
    "..XX.XXXX.XX..",
    "..XX..XX..XX..",
    "...X..XX..X...",
    "...X...X..X...",
    "..............",
  ],
  snowfest: [
    "X....XXXX....X",
    "....XXXXXX....",
    ".X..XXoXXX..X.",
    "....XXXXXX....",
    "...XXXXXXXX...",
    "X..XXXXXXXX..X",
    "...XXXXXXXX...",
    "..XXXXXXXXXX..",
    ".X.XXXXXXXX.X.",
    "..XXXXXXXXXX..",
  ],
};

/** 全紋章が 10行 × 14列であることを確認する */
export function assertEmblems() {
  const bad = [];
  for (const [name, rows] of Object.entries(EMBLEMS)) {
    if (rows.length !== 10) bad.push(`${name}: ${rows.length}行 (10行であるべき)`);
    rows.forEach((r, i) => {
      if (r.length !== 14) bad.push(`${name} の ${i}行目: ${r.length}文字 (14文字であるべき)`);
      if (/[^.Xo#]/.test(r)) bad.push(`${name} の ${i}行目に未知の文字: ${r}`);
    });
  }
  return bad;
}
