/**
 * TNTの帯に描く紋章。すべて 6行 × 12列。
 *   "."  帯の地の色 (描かない)
 *   "X"  主色 (ink)
 *   "o"  明色 (inkLight)
 *   "#"  暗色 (inkDark)
 *
 * 16x16 のうち帯に使えるのは 6行しかないので、塗りつぶしを増やすと
 * ただの塊にしか見えなくなる。輪郭と余白で形を出すこと。
 */
export const EMBLEMS = {
  // ── 基本 ──────────────────────────────────────────────
  tnt: [
    "............",
    "XXX.X..X.XXX",
    ".X..XX.X..X.",
    ".X..X.XX..X.",
    ".X..X..X..X.",
    "............",
  ],
  dynamite: [
    ".......ooX..",
    "......o.....",
    "....XXXX....",
    "....XooX....",
    "....XooX....",
    "....XXXX....",
  ],

  // ── 核・破滅系 ────────────────────────────────────────
  radiation: [
    "....XXXX....",
    "....XXXX....",
    ".....##.....",
    "..XX.##.XX..",
    ".XXXX..XXXX.",
    "XXXXX..XXXXX",
  ],
  mushroom: [
    "..XXXXXXXX..",
    ".XXXXXXXXXX.",
    "...XXXXXX...",
    "....XXXX....",
    "....XXXX....",
    "..XXXXXXXX..",
  ],
  mushroom_ring: [
    "..XXXXXXXX..",
    "o.XXXXXXXX.o",
    "o..XXXXXX..o",
    "o...XXXX...o",
    "....XXXX....",
    "..XXXXXXXX..",
  ],
  bomb: [
    ".........oX.",
    "..XXXX..oX..",
    ".XXXXXX.X...",
    ".XXXXXXX....",
    ".XXXXXX.....",
    "..XXXX......",
  ],
  atom: [
    "..XXXXXXXX..",
    ".X........X.",
    "o....XX....o",
    "o....XX....o",
    ".X........X.",
    "..XXXXXXXX..",
  ],
  skull: [
    "...XXXXXX...",
    "..XXXXXXXX..",
    "..X..XX..X..",
    "..XXXXXXXX..",
    "...X.XX.X...",
    "...XXXXXX...",
  ],
  bigskull: [
    "..XXXXXXXX..",
    ".XXXXXXXXXX.",
    ".X.oo..oo.X.",
    ".XXXXXXXXXX.",
    "..X.X..X.X..",
    "..XXXXXXXX..",
  ],

  // ── 温度・天候 ────────────────────────────────────────
  flame: [
    ".....XX.....",
    "....X.XX....",
    "...XX..XX...",
    "..XX.oo.XX..",
    "..XX.oo.XX..",
    "...XXXXXX...",
  ],
  lava: [
    "............",
    "....X.......",
    "..X.X..X....",
    ".XXXXXXXXXX.",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
  ],
  snowflake: [
    "..X..XX..X..",
    "...X.XX.X...",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "...X.XX.X...",
    "..X..XX..X..",
  ],
  glacier: [
    "..XX........",
    ".XXXX...XX..",
    "XXXXXX.XXXX.",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
  ],
  droplet: [
    ".....XX.....",
    "....XXXX....",
    "...XXXXXX...",
    "..XXXooXXX..",
    "..XXXXXXXX..",
    "...XXXXXX...",
  ],
  wave: [
    "......XXX...",
    "....XXXXXX..",
    "...XXX..XXX.",
    "..XX.....XX.",
    "XXXXXXXXXXXX",
    ".XXXXXXXXXX.",
  ],
  bolt: [
    ".....XXX....",
    "....XXX.....",
    "...XXXXX....",
    "......XXX...",
    ".....XXX....",
    "....XXX.....",
  ],
  cloud: [
    "...XXXXX....",
    "..XXXXXXXX..",
    ".XXXXXXXXXX.",
    "..XXXXXXXX..",
    "..o..o..o...",
    ".o..o..o....",
  ],
  sun: [
    "..X..XX..X..",
    "...XXXXXX...",
    ".X.XooooX.X.",
    "XX.XooooX.XX",
    "...XXXXXX...",
    "..X..XX..X..",
  ],
  moon: [
    "...XXXX...o.",
    "..XXXX......",
    ".XXXX....o..",
    ".XXXX.......",
    "..XXXX...o..",
    "...XXXX.....",
  ],
  daynight: [
    "..XXX...oooo",
    ".XXXXX.oo..o",
    "XXXXXXXo....",
    "XXXXXXXo....",
    ".XXXXX.oo..o",
    "..XXX...oooo",
  ],

  // ── 力・移動 ──────────────────────────────────────────
  arrow_down: [
    ".....XX.....",
    ".....XX.....",
    "..XXXXXXXX..",
    "...XXXXXX...",
    "....XXXX....",
    ".....XX.....",
  ],
  arrow_up: [
    ".....XX.....",
    "....XXXX....",
    "...XXXXXX...",
    "..XXXXXXXX..",
    ".....XX.....",
    ".....XX.....",
  ],
  rocket: [
    ".....XX.....",
    "....XooX....",
    "....XooX....",
    "....XooX....",
    "..XXXXXXXX..",
    "...o.oo.o...",
  ],
  speed: [
    "..XX...XX...",
    ".XXX..XXX...",
    "XXX..XXX....",
    "XXX..XXX....",
    ".XXX..XXX...",
    "..XX...XX...",
  ],
  bounce: [
    "....XXXX....",
    "...XXXXXX...",
    "...XXXXXX...",
    "....XXXX....",
    "............",
    "oooooooooooo",
  ],
  slime_face: [
    "..XXXXXXXX..",
    ".XXXXXXXXXX.",
    ".XX..XX..XX.",
    ".XXXXXXXXXX.",
    ".XX.XXXX.XX.",
    "..XXXXXXXX..",
  ],
  magnet: [
    "..XXXXXXXX..",
    ".XXXXXXXXXX.",
    "XXXX....XXXX",
    "XXX......XXX",
    "ooo......ooo",
    "ooo......ooo",
  ],
  question: [
    ".XXX....XXX.",
    "X...X..X...X",
    "...X......X.",
    "..X......X..",
    "............",
    "..X......X..",
  ],
  void: [
    "...oooooo...",
    "..oo....oo..",
    ".oo......oo.",
    ".oo......oo.",
    "..oo....oo..",
    "...oooooo...",
  ],
  suction: [
    "XX........XX",
    ".XX......XX.",
    "..XXX..XXX..",
    "..XXX..XXX..",
    ".XX......XX.",
    "XX........XX",
  ],
  portal: [
    "...XXXXXX...",
    ".XXooooooXX.",
    "XXoo.XX.ooXX",
    "XXoo.XX.ooXX",
    ".XXooooooXX.",
    "...XXXXXX...",
  ],
  island: [
    "...XXXXXX...",
    "..XXXXXXXX..",
    "..XXXXXXXX..",
    "...XXXXXX...",
    "....XXXX....",
    ".....XX.....",
  ],
  swap: [
    "..X.........",
    ".XXXXXXXXXX.",
    "..X.........",
    ".........X..",
    ".XXXXXXXXXX.",
    ".........X..",
  ],
  beam: [
    "XXXXXXXXXXXX",
    "..XXXXXXXX..",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "..XXXXXXXX..",
    "XXXXXXXXXXXX",
  ],

  // ── 生き物 ────────────────────────────────────────────
  heart: [
    "..XX....XX..",
    ".XXXX..XXXX.",
    "XXXXXXXXXXXX",
    ".XXXXXXXXXX.",
    "..XXXXXXXX..",
    "....XXXX....",
  ],
  creeper: [
    "..XXXXXXXX..",
    "..X..XX..X..",
    "..X..XX..X..",
    "..XXX..XXX..",
    "..XX.XX.XX..",
    "..XX.XX.XX..",
  ],
  bee: [
    ".oo......oo.",
    "..o......o..",
    "...XXXXXX...",
    "...X.XX.X...",
    "...XXXXXX...",
    ".....XX.....",
  ],
  drip: [
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    ".X...XX...X.",
    ".X...XX...X.",
    "..X..XX..X..",
    "..o...o..o..",
  ],
  paw: [
    ".XX..XX..XX.",
    ".XX..XX..XX.",
    "............",
    "...XXXXXX...",
    "..XXXXXXXX..",
    "...XXXXXX...",
  ],
  snowman: [
    "....XXXX....",
    "...X#XX#X...",
    "....XXXX....",
    "..XXXXXXXX..",
    ".XX.XXXX.XX.",
    "..XXXXXXXX..",
  ],
  ghost: [
    "...XXXXXX...",
    "..X......X..",
    "..X.XX.X.X..",
    "..X......X..",
    "..X......X..",
    "..X.X.X.XX..",
  ],
  ufo: [
    "....XXXX....",
    "...XooooX...",
    ".XXXXXXXXXX.",
    "XXoXoXoXoXXX",
    ".XXXXXXXXXX.",
    "..o..o..o...",
  ],
  web: [
    "X....XX....X",
    ".X..XXXX..X.",
    "..XXXXXXXX..",
    "..XXXXXXXX..",
    ".X..XXXX..X.",
    "X....XX....X",
  ],
  flask: [
    ".....XX.....",
    ".....XX.....",
    "....XXXX....",
    "...XooooX...",
    "..XXooooXX..",
    "...XXXXXX...",
  ],
  eye: [
    "...XXXXXX...",
    ".XXooooooXX.",
    "XXoo#XX#ooXX",
    "XXoo#XX#ooXX",
    ".XXooooooXX.",
    "...XXXXXX...",
  ],

  // ── 自然・地形 ────────────────────────────────────────
  grass: [
    "..X...X...X.",
    ".XXX.XXX.XXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
  ],
  cactus: [
    ".....XX.....",
    "XX...XX...XX",
    "XX...XX...XX",
    "XXXXXXXXXXXX",
    ".XX..XX..XX.",
    ".....XX.....",
  ],
  dune: [
    "............",
    "...XXX......",
    "..XXXXX..XXX",
    ".XXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
  ],
  crack: [
    ".....X......",
    "....XX......",
    "....X..XX...",
    "...XX...X...",
    "..XX....XX..",
    "..X......X..",
  ],
  meteor: [
    "o...........",
    ".oo.........",
    "..ooo.XXXX..",
    "...ooXXXXXX.",
    "....XXXXXXX.",
    ".....XXXXX..",
  ],
  hole: [
    "..XXXXXXXX..",
    ".X########X.",
    "X##########X",
    "X##########X",
    ".X########X.",
    "..XXXXXXXX..",
  ],
  crystal: [
    ".....XX.....",
    "....XXXX....",
    "...XXooXX...",
    "..XXXooXXX..",
    "...XXooXX...",
    "....XXXX....",
  ],

  // ── 道具・その他 ──────────────────────────────────────
  gem: [
    "...XXXXXX...",
    "..XXoooXXX..",
    ".XXoooooXXX.",
    "..XXoooXXX..",
    "...XXoXXX...",
    "....XXXX....",
  ],
  clover: [
    "..XX..XX....",
    ".XXXXXXXX...",
    ".XXXXXXXX.o.",
    "..XXXXXX.o..",
    "....XX..o...",
    "....XX......",
  ],
  star: [
    ".....XX.....",
    "....XXXX....",
    "XXXXXXXXXXXX",
    ".XXXXXXXXXX.",
    "..XXXXXXXX..",
    ".XXX....XXX.",
  ],
  firework: [
    "..o..X..o...",
    "X..X.X.X..X.",
    ".X..XXX..X..",
    "..XXXXXXX...",
    "....XXX.....",
    "....XXX.....",
  ],
  confetti: [
    ".X...o....X.",
    "...o...XX...",
    ".X..oo....o.",
    "X...X...o...",
    "..oX...X..XX",
    ".o...X...o..",
  ],
  note: [
    "....X....X..",
    "....X....X..",
    "....X....X..",
    "..XXX..XXX..",
    ".XXXX.XXXX..",
    ".XXX...XXX..",
  ],
  disco: [
    "...XXXXXX...",
    "..XoXoXoXX..",
    ".XXoXoXoXXX.",
    ".XoXoXoXoXX.",
    "..XoXoXoXX..",
    "...XXXXXX...",
  ],
  brick: [
    "XXXXX.XXXXX.",
    "XXXXX.XXXXX.",
    "............",
    "XX.XXXXX.XXX",
    "XX.XXXXX.XXX",
    "............",
  ],
  furnace: [
    ".XXXXXXXXXX.",
    ".X........X.",
    ".X..XXXX..X.",
    ".X.oooooo.X.",
    ".X.oooooo.X.",
    ".XXXXXXXXXX.",
  ],
  wheat: [
    "..X..XX..X..",
    ".XXX.XX.XXX.",
    "..X.XXXX.X..",
    ".XXX.XX.XXX.",
    "..X..XX..X..",
    ".....XX.....",
  ],
  cutlery: [
    ".X.X.X..XX..",
    ".X.X.X..XX..",
    ".XXXXX..XX..",
    "..XXX...XX..",
    "..XXX...XX..",
    "..XXX...XX..",
  ],
  orb: [
    "o...XXXX...o",
    "..XXXXXXXX..",
    ".XXXXXXXXXX.",
    ".XXXXXXXXXX.",
    "..XXXXXXXX..",
    "o...XXXX...o",
  ],
  arrows: [
    "........X...",
    "X.......XX..",
    "XXXXXXXXXXX.",
    "XXXXXXXXXXX.",
    "X.......XX..",
    "........X...",
  ],
};

/** 全紋章が 6行 × 12列であることを確認する */
export function assertEmblems() {
  const bad = [];
  for (const [name, rows] of Object.entries(EMBLEMS)) {
    if (rows.length !== 6) bad.push(`${name}: ${rows.length}行 (6行であるべき)`);
    rows.forEach((r, i) => {
      if (r.length !== 12) bad.push(`${name} の ${i}行目: ${r.length}文字 (12文字であるべき)`);
      if (/[^.Xo#]/.test(r)) bad.push(`${name} の ${i}行目に未知の文字: ${r}`);
    });
  }
  return bad;
}
