/**
 * このファイルは自動生成される (tools/build.mjs)。直接編集しないこと。
 *
 * 元になっているもの: data/tnt/*.mjs と BP/scripts/effects/*.js
 */
import { collapseEffect, drillEffect, replicatorEffect, singularityEffect, timestopEffect } from "./chaos.js";
import { bridgeEffect, flattenEffect, paveEffect, quarryEffect, scaffoldEffect, shelterEffect, stairwayEffect, towerEffect, tunnelEffect, wallEffect } from "./construction.js";
import { bigbangEffect, cometEffect, galaxyEffect, nebulaEffect, neutronEffect, solarflareEffect, supernovaEffect, wormholeEffect } from "./cosmic.js";
import { animalEffect, beeEffect, catEffect, golemEffect, phantomEffect, snowgolemEffect, summonEffect, ufoEffect, villagerEffect } from "./creature.js";
import { acidEffect, crystalEffect, darknessEffect, fireEffect, iceEffect, iceageEffect, lavaEffect, poisonEffect, sandstormEffect, scorchedEffect, steamEffect, stormEffect, thunderEffect, tsunamiEffect, vacuumEffect, waterEffect } from "./elemental.js";
import { bunkerEffect, clusterEffect, empEffect, flakEffect, gasEffect, mineEffect, missileEffect, napalmEffect, shrapnelEffect, smokeEffect } from "./military.js";
import { antiGravityEffect, beamEffect, blackholeEffect, bouncyEffect, chorusEffect, dashEffect, elevatorEffect, endermanEffect, gravityEffect, magnetBurstEffect, slimeEffect, speedEffect, swapEffect, teleportEffect } from "./motion.js";
import { antimatterEffect, armageddonEffect, hydrogenBombEffect, nukeEffect, tsarBombaEffect, ultraNukeEffect } from "./nuclear.js";
import { arrowEffect, auroraEffect, confettiEffect, confusionEffect, curseEffect, discoEffect, fireworksEffect, meteorEffect, musicEffect, rainbowEffect, snowfestEffect } from "./spectacle.js";
import { builderEffect, cactusEffect, caveEffect, desertEffect, earthquakeEffect, forestEffect, grassEffect, harvestEffect, honeyEffect, lakeEffect, netherEffect, obsidianEffect, shaftEffect, smelterEffect } from "./terrain.js";
import { beaconEffect, daynightEffect, feastEffect, fortuneEffect, glowEffect, healEffect, invisibilityEffect, supplyEffect, surveyEffect, torchEffect, treasureEffect, webEffect, xpEffect } from "./utility.js";

/** 効果の名前から実体を引くための表 */
export const EFFECTS = {
  acidEffect,
  animalEffect,
  antiGravityEffect,
  antimatterEffect,
  armageddonEffect,
  arrowEffect,
  auroraEffect,
  beaconEffect,
  beamEffect,
  beeEffect,
  bigbangEffect,
  blackholeEffect,
  bouncyEffect,
  bridgeEffect,
  builderEffect,
  bunkerEffect,
  cactusEffect,
  catEffect,
  caveEffect,
  chorusEffect,
  clusterEffect,
  collapseEffect,
  cometEffect,
  confettiEffect,
  confusionEffect,
  crystalEffect,
  curseEffect,
  darknessEffect,
  dashEffect,
  daynightEffect,
  desertEffect,
  discoEffect,
  drillEffect,
  earthquakeEffect,
  elevatorEffect,
  empEffect,
  endermanEffect,
  feastEffect,
  fireEffect,
  fireworksEffect,
  flakEffect,
  flattenEffect,
  forestEffect,
  fortuneEffect,
  galaxyEffect,
  gasEffect,
  glowEffect,
  golemEffect,
  grassEffect,
  gravityEffect,
  harvestEffect,
  healEffect,
  honeyEffect,
  hydrogenBombEffect,
  iceEffect,
  iceageEffect,
  invisibilityEffect,
  lakeEffect,
  lavaEffect,
  magnetBurstEffect,
  meteorEffect,
  mineEffect,
  missileEffect,
  musicEffect,
  napalmEffect,
  nebulaEffect,
  netherEffect,
  neutronEffect,
  nukeEffect,
  obsidianEffect,
  paveEffect,
  phantomEffect,
  poisonEffect,
  quarryEffect,
  rainbowEffect,
  replicatorEffect,
  sandstormEffect,
  scaffoldEffect,
  scorchedEffect,
  shaftEffect,
  shelterEffect,
  shrapnelEffect,
  singularityEffect,
  slimeEffect,
  smelterEffect,
  smokeEffect,
  snowfestEffect,
  snowgolemEffect,
  solarflareEffect,
  speedEffect,
  stairwayEffect,
  steamEffect,
  stormEffect,
  summonEffect,
  supernovaEffect,
  supplyEffect,
  surveyEffect,
  swapEffect,
  teleportEffect,
  thunderEffect,
  timestopEffect,
  torchEffect,
  towerEffect,
  treasureEffect,
  tsarBombaEffect,
  tsunamiEffect,
  tunnelEffect,
  ufoEffect,
  ultraNukeEffect,
  vacuumEffect,
  villagerEffect,
  wallEffect,
  waterEffect,
  webEffect,
  wormholeEffect,
  xpEffect,
};
